# Generated by Django 4.1.1 on 2022-10-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='hello', max_length=256),
            preserve_default=False,
        ),
    ]
