# Generated by Django 4.1.1 on 2022-10-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
